---
- name: Update apt cache
  sudo: yes
  apt: update_cache=yes cache_valid_time=43200
  tags: common

- name: Update language
  sudo: yes
  apt: pkg=language-pack-en
  tags: common

- name: Install packages
  apt: pkg={{ item }}
  sudo: yes
  with_items:
    - build-essential
    - curl
    - git
    - ruby
    - g++
    - libkrb5-dev
    - libpng-dev
    - libfontconfig-dev
    - libssl-dev
    - python-pip
  tags: packages